#spring:
#  datasource:
#    url: #
#    username: #
#    password: #
#    driver-class-name: com.informix.jdbc.IfxDriver
#  jpa:
#   show-sql = true
#
#
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
#
#
#server:
#  port: 8085
#
#jpa:
#  hibernate:
#    ddl-auto: none
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.InformixDialect
#
